### PR TITLE
MNT: rerender

### LINKED ISSUE #48: @conda-forge-admin rerender
### Additional comment:

_No response_

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #48.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

Fixes #48

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by beckermr** [comment]
@wolfv this should pick up the new runtime pinnings for the compilers

@isuruf would you suggest a repodata patch to try and fix recent builds that have the problematic >=10 pinnings across all of conda-forge?

**Comment by beckermr** [comment]
Ouch. Maybe a repodata patch is easier here too @wolfv

**Comment by wolfv** [comment]
Actually we have a libmamba output now in the mamba feedstock. Should maybe archive this feedstock

**Comment by beckermr** [comment]
Yeah feel free to go ahead!

**Pull request closed without merging**
